server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://47.118.51.155:3306/spring_tansiactional?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: rtuser
    password: gs@2022#
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*.xml


